Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,16 +25,16 @@ jobs:
             sudo docker-php-ext-enable pdo_mysql
             echo -e "127.0.0.1 db" | sudo tee -a /etc/hosts
             echo 'memory_limit = -1' | sudo tee -a /usr/local/etc/php/conf.d/docker-php-memlimit.ini
-      - run:
-          name: Wait untill MySQL is ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z db 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+      # - run:
+      #     name: Wait untill MySQL is ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z db 3306 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for MySQL && exit 1
       - run: 
           name: Create database
           command: |
